### ISSUE TITLE
[Question]: Maintain workflow?

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [johncardiologs/dependent-issues#4]
Hi @johncardiologs upstream has unfortunately been archived 
see https://github.com/z0al/dependent-issues/pull/546#issuecomment-1736256946

I would like to know if u have interest in maintaining this fork. I would really love to use this workflow but i dont have any experience with typescript.

I hope this doesnt come over as rude to you but i saw that u opened two crucial PR's to enhance the workflow so thats why i reached out

**Comment by johncardiologs** [comment]
Hey there, thanks for reaching out. While I don't think I would quite have the time or motivation to maintain something like this, I see there are actually quite a few alternatives out there. Here's one I found just from a quick search: https://github.com/gregsdennis/dependencies-action
There are a number of folks who expressed interest in this on this issue: https://github.com/isaacs/github/issues/959
Good luck!

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Thankyou very much for the help @johncardiologs
